/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.11).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.CreditCard;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-10-25T17:23:10.744Z[GMT]")
@Api(value = "isValidCreditCard", description = "the isValidCreditCard API")
public interface IsValidCreditCardApi {

    @ApiOperation(value = "", nickname = "isValid", notes = "return whether the given credit card is accepted at the pizza store      ", tags={ "Payment API", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "returned successfully"),
        @ApiResponse(code = 404, message = "bad input") })
    @RequestMapping(value = "/isValidCreditCard",
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Boolean> isValid(
        @ApiParam(value = "the credit card",required=true) @Valid @RequestBody CreditCard creditCard);



    /*
    @ApiParam(value = "the number of adult") @Valid @RequestParam(value = "Adult", required = false) Integer adult,
      @ApiParam(value = "the number of child") @Valid @RequestParam(value = "Child", required = false) Integer child);
     */

}
