/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.13).
 * https://github.com/swagger-api/swagger-codegen Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.CreditCard;
import io.swagger.annotations.*;
import io.swagger.model.Order;
import io.swagger.model.Payment;
import io.swagger.model.Receipt;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-11-12T01:52:56.484Z[GMT]")
@Api(value = "generateReceipt", description = "the generateReceipt API")
public interface GenerateReceiptApi {

  @ApiOperation(value = "", nickname = "generateReceipt", notes = "generate a receipt for a valid transaction ", tags = {
      "Payment API",})
  @ApiResponses(value = {
      @ApiResponse(code = 200, message = "returned successfully"),
      @ApiResponse(code = 404, message = "bad input")})
  @RequestMapping(value = "/generateReceipt",
      consumes = { "application/json" },
      method = RequestMethod.POST)
  ResponseEntity<Receipt> generateReceipt(
      @ApiParam(value = "credit card", required = true) @Valid @RequestBody CreditCard creditCard,
      @ApiParam(value = "amount expected to pay", required = true) @Valid @RequestBody Double amount,
      @ApiParam(value = "order", required = true) @Valid @RequestBody io.swagger.models.Order order,
      @ApiParam(value = "payment from customer", required = true) @Valid @RequestBody Payment payment);

}
