/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.11).
 * https://github.com/swagger-api/swagger-codegen Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.PizzaSize;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-10-11T06:27:17.732Z[GMT]")
@Api(value = "pizzasize", description = "the pizza size API")
public interface PizzaSizeApi {

  @ApiOperation(value = "adds a pizza size", nickname = "addPizzaSize", notes = "Adds a pizza size to the system", tags = {
      "PizzaSize",})
  @ApiResponses(value = {
      @ApiResponse(code = 201, message = "pizza size created"),
      @ApiResponse(code = 400, message = "invalid input, object invalid"),
      @ApiResponse(code = 409, message = "an existing pizza size already exists")})
  @RequestMapping(value = "/pizzasizes",
      consumes = {"application/json"},
      method = RequestMethod.POST)
  ResponseEntity<Void> addPizzaSize(
      @ApiParam(value = "Pizza size to add") @Valid @RequestBody PizzaSize body);


  @ApiOperation(value = "searches pizza sizes", nickname = "searchPizzaSizes", notes = "By passing in the appropriate options, you can search for available pizza sizes in the system ", response = PizzaSize.class, responseContainer = "List", tags = {
      "PizzaSize",})
  @ApiResponses(value = {
      @ApiResponse(code = 200, message = "search results matching criteria", response = PizzaSize.class, responseContainer = "List"),
      @ApiResponse(code = 400, message = "bad input parameter")})
  @RequestMapping(value = "/pizzasizes",
      produces = {"application/json"},
      method = RequestMethod.GET)
  ResponseEntity<List<PizzaSize>> searchPizzaSize(
      @ApiParam(value = "pass an optional search id for looking up pizza size") @Valid @RequestParam(value = "searchId", required = false) Integer searchId);

}
