/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.11).
 * https://github.com/swagger-api/swagger-codegen Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.model.Eater;
import io.swagger.model.SuggestedPizzaSizeOrder;
import javax.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-10-23T18:23:25.075Z[GMT]")
@Api(value = "suggestpizza", description = "the suggestpizza API")
public interface Suggestpizza {

  @ApiOperation(value = "return a suggested order given the number and type of eaters.", nickname = "getOrder", notes = "Given the number and type of eaters, it provides info on how many pizzas to ordeer.  ", tags = {
      "SuggestPizzaOrder",})
  @ApiResponses(value = {
      @ApiResponse(code = 200, message = "The pizza number and size to order"),
      @ApiResponse(code = 400, message = "Invalid input， negative adults/children")})
  @RequestMapping(value = "/suggestpizza",
      consumes = {"application/json"},
      method = RequestMethod.POST)
  ResponseEntity<SuggestedPizzaSizeOrder> getOrder(
      @ApiParam(value = "the number of adult") @Valid @RequestBody Eater eater);

}
